### ISSUE TITLE
開啓IDS候沒有Init

### ISSUE THREAD

**Issue by nfurobotlab** [nfu-irs-lab/robotic-arm-control-panel#108]
### Bug 描述
如題

### 重現步驟

1. 按下攝影機界面的開始

### 預期的行爲
先Init()再Open()

### 備註
https://github.com/nfu-irs-lab/hiwinrobot/blob/main/MainForm/MainForm.cs#L705-L709

**Comment by ziteh** [comment]
#111
等待發行
